# Generated by Django 5.0.7 on 2024-08-04 21:50

import common.uuid
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "external_id",
                    models.UUIDField(default=common.uuid.unique_uuid4, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                ("auth_secret", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("is_suspended", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlatformUserEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("external_id", models.UUIDField(default=common.uuid.unique_uuid4)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=14, null=True)),
                ("auth_secret", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("is_suspended", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="platformuser",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "account_platformuserevent" ("auth_secret", "created", "email", "external_id", "id", "is_active", "is_admin", "is_deleted", "is_suspended", "last_login", "modified", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "version") VALUES (NEW."auth_secret", NEW."created", NEW."email", NEW."external_id", NEW."id", NEW."is_active", NEW."is_admin", NEW."is_deleted", NEW."is_suspended", NEW."last_login", NEW."modified", NEW."password", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."version"); RETURN NULL;',
                    hash="0958486298841a2a2231270a062408bf92683ad8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_1cddf",
                    table="account_platformuser",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="platformuser",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "account_platformuserevent" ("auth_secret", "created", "email", "external_id", "id", "is_active", "is_admin", "is_deleted", "is_suspended", "last_login", "modified", "password", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "version") VALUES (NEW."auth_secret", NEW."created", NEW."email", NEW."external_id", NEW."id", NEW."is_active", NEW."is_admin", NEW."is_deleted", NEW."is_suspended", NEW."last_login", NEW."modified", NEW."password", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."version"); RETURN NULL;',
                    hash="dcf37ebd3025ad22d6bb0eb4efaca47aaba8d14d",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_e3bfc",
                    table="account_platformuser",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="platformuserevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="platformuserevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
