# Generated by Django 5.0.7 on 2024-08-05 07:19

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("profile_pic", models.JSONField(default=dict)),
                ("profile_name", models.CharField(blank=True, max_length=32)),
                ("is_suspended", models.BooleanField(default=False)),
                (
                    "platform_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="external_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerProfileEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("profile_pic", models.JSONField(default=dict)),
                ("profile_name", models.CharField(blank=True, max_length=32)),
                ("is_suspended", models.BooleanField(default=False)),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="profile_player.playerprofile",
                    ),
                ),
                (
                    "platform_user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                        to_field="external_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="playerprofile",
            index=models.Index(
                fields=["platform_user"], name="profile_pla_platfor_93022d_idx"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="playerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "profile_player_playerprofileevent" ("created", "id", "is_deleted", "is_suspended", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_user_id", "profile_name", "profile_pic", "version") VALUES (NEW."created", NEW."id", NEW."is_deleted", NEW."is_suspended", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."platform_user_id", NEW."profile_name", NEW."profile_pic", NEW."version"); RETURN NULL;',
                    hash="a6f51ee2870b40bf0e26ae15a9335ac88dd715f0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_9018f",
                    table="profile_player_playerprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="playerprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "profile_player_playerprofileevent" ("created", "id", "is_deleted", "is_suspended", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform_user_id", "profile_name", "profile_pic", "version") VALUES (NEW."created", NEW."id", NEW."is_deleted", NEW."is_suspended", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."platform_user_id", NEW."profile_name", NEW."profile_pic", NEW."version"); RETURN NULL;',
                    hash="9a29f11ba823395be6c1d6f428646bf2dd3d8db8",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_d494d",
                    table="profile_player_playerprofile",
                    when="AFTER",
                ),
            ),
        ),
    ]
