# Generated by Django 5.0.7 on 2026-08-30 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("game", "0008_team_unique_spectator_team_per_game"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(default=common.uuid.unique_uuid4, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("role", models.PositiveIntegerField(choices=[(1, "PLAYER"), (2, "GAME_MASTER")])),
                ("object_key", models.CharField(max_length=512)),
                ("asset_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=100)),
                ("status", models.PositiveIntegerField(choices=[(1, "PENDING"), (2, "UPLOADED")], default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media_assets", to="game.game"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["game"], name="media_asset_game_id_e847ed_idx"),
                    models.Index(fields=["status"], name="media_asset_status_676b91_idx"),
                ],
            },
        ),
    ]
