version: '3'

services:
  q_yaar_core:
    restart: always
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./Dockerfile-dev
    ports:
      - "8000:8000"
    depends_on:
      - q_yaar_redisearch
      - q_yaar_db
    networks:
      - backend
    environment:
      - IS_LOCAL=True
      - IS_PREPROD=False
      - IS_PROD=False
      - DEBUG=True
      - DATABASE_URL=postgres://q_yaar_user:q_yaar_password@q_yaar_db:5432/q_yaar_db
      - REDIS_URL=redis://q_yaar_redisearch:6380/0
      - TEST_DB_NAME=q_yaar_db_test
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  q_yaar_fast_worker:
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./Dockerfile-dev
    command: celery -A esamudaay_platform worker -E -l info --concurrency=8 --pool -n fast_worker@qyaar.com  -Q example
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
    networks:
      - backend

  q_yaar_slow_worker:
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./Dockerfile-dev
    command: celery -A esamudaay_platform worker -E -l info --concurrency=8 --pool -n slow_worker@qyaar.com  -Q example
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
    networks:
      - backend

  q_yaar_celery_beat:
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./Dockerfile-dev
    command: celery -A esamudaay_platform beat -l debug
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
      - q_yaar_db
    networks:
      - backend

  q_yaar_db:
    image: postgres
    ports:
      - "5434:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=q_yaar_db
      - POSTGRES_USER=q_yaar_user
      - POSTGRES_PASSWORD=q_yaar_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  q_yaar_redisearch:
    image: redislabs/redisearch:latest
    ports:
      - "6380:6380"
    expose:
      - "5432"
    volumes:
      - ./redis:/data
    command:
      [
        "redis-server",
        "--port",
        "6380",
        "--loadmodule",
        "/usr/lib/redis/modules/redisearch.so",
        "--appendonly",
        "yes",
        "--aof-use-rdb-preamble",
        "yes"
      ]

networks:
  backend:


volumes:
  redisdata:
  dbdata:
