version: '3'

services:
  q_yaar_core:
    restart: always
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./docker/Dockerfile-dev
    env_file: ./../q_yaar_platform/.env
    ports:
      - "8000:8000"
    depends_on:
      - q_yaar_redisearch
      - q_yaar_db
    networks:
      - backend
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  q_yaar_fast_worker:
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./docker/Dockerfile-dev
    command: celery -A q_yaar worker -E -l info --concurrency=8 --pool=prefork -n fast_worker@qyaar.com  -Q example
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
    networks:
      - backend

  q_yaar_slow_worker:
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./docker/Dockerfile-dev
    command: celery -A q_yaar worker -E -l info --concurrency=8 --pool=prefork -n slow_worker@qyaar.com  -Q example
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
    networks:
      - backend

  q_yaar_celery_beat:
    build: 
      context: ./../q_yaar_platform
      dockerfile: ./docker/Dockerfile-dev
    command: celery -A q_yaar beat -l debug
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
      - q_yaar_db
    networks:
      - backend

  q_yaar_db:
    image: postgres
    env_file: ./../q_yaar_platform/.env
    ports:
      - "5434:5432"
    expose:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  q_yaar_redisearch:
    image: redislabs/redisearch:latest
    ports:
      - "6380:6380"
    expose:
      - "6380"
    volumes:
      - ./redis:/data
    command:
      [
        "redis-server",
        "--port",
        "6380",
        "--loadmodule",
        "/usr/lib/redis/modules/redisearch.so",
        "--appendonly",
        "yes",
        "--aof-use-rdb-preamble",
        "yes"
      ]

networks:
  backend:


volumes:
  redisdata:
  dbdata:
