version: '3'

services:
  q_yaar_core:
    restart: always
    build: ./../q_yaar_platform
    ports:
      - "8000:8000"
    depends_on:
      - q_yaar_redisearch
      - q_yaar_db
    networks:
      - backend
    env_file: ./../q_yaar_platform/.env
    command: gunicorn q_yaar.wsgi:application -w 4 -b :8000

  q_yaar_fast_worker:
    build: ./../q_yaar_platform
    command: celery -A q_yaar worker -E -l info --concurrency=8 --pool=prefork -n fast_worker@qyaar.com  -Q example
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
    networks:
      - backend

  q_yaar_slow_worker:
    build: ./../q_yaar_platform
    command: celery -A q_yaar worker -E -l info --concurrency=8 --pool=prefork -n slow_worker@qyaar.com  -Q default
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
    networks:
      - backend

  q_yaar_celery_beat:
    build: ./../q_yaar_platform
    command: celery -A q_yaar beat -l debug
    env_file: ./../q_yaar_platform/.env
    depends_on:
      - q_yaar_redisearch
      - q_yaar_db
    networks:
      - backend

  q_yaar_db:
    image: postgres
    expose:
      - "5434"
    environment:
      - POSTGRES_DB=q_yaar_db
      - POSTGRES_USER=q_yaar_user
      - POSTGRES_PASSWORD=q_yaar_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  q_yaar_redisearch:
    image: redislabs/redisearch:latest
    ports:
      - "6380:6380"
    volumes:
      - ./redis:/data
    command:
      [
        "redis-server",
        "--port",
        "6380",
        "--loadmodule",
        "/usr/lib/redis/modules/redisearch.so",
        "--appendonly",
        "yes",
        "--aof-use-rdb-preamble",
        "yes"
      ]

networks:
  backend:


volumes:
  redisdata:
  dbdata:
